// prisma/seed.ts
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  await prisma.broker.createMany({
    data: [
      {
        name: "Jason Hammock",
        email: "jason.hammock@cbre.com",
        organization: "CBRE",
        phone: "405-315-0725",
        location: "Oklahoma",
        type: "Industrial",
        lastFollowUp: new Date("2025-03-10"),
        nextFollowUp: new Date("2025-03-10"),
        userId: null,
      },
      {
        name: "David Glasgow",
        email: "david.glasgow@cbre.com",
        organization: "CBRE",
        phone: "918-798-8787",
        location: "Oklahoma",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Jake Miller",
        email: "jake.miller@cbre.com",
        organization: "CBRE",
        phone: "208-589-2951",
        location: "Idaho",
        type: "Industrial",
        lastFollowUp: new Date("2025-03-03"),
        nextFollowUp: new Date("2025-03-03"),
        userId: null,
      },
      {
        name: "Eric Bennett",
        email: "eric.bennett@cbre.com",
        organization: "CBRE",
        phone: "775-813-3794",
        location: "Reno",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Aiman Noursoultanova",
        email: "aiman.noursoultanova@cbre.com",
        organization: "CBRE",
        phone: "775-233-7049",
        location: "Reno",
        type: "Multifamily",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Tomi Jo Lynch",
        email: "TomiJo.Lynch@cbre.com",
        organization: "CBRE",
        phone: "office: 775-321-4484; cell: 775-530-2621",
        location: "Reno",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Chris Liddell",
        email: "chris.liddell@cbre.com",
        organization: "CBRE",
        phone: "801-870-5841",
        location: "Utah",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Mark Jensen",
        email: "mjensen@northmarq.com",
        organization: "Northmark",
        phone: "801-897-3663",
        location: "Utah",
        type: "Multifamily",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Rawley Nielsen",
        email: "rnielsen@northmarq.com",
        organization: "Northmark",
        phone: "415-407-3942",
        location: "Utah",
        type: "Multifamily",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Wes Gotcher",
        email: "wes@moriahgroup.net",
        organization: "Moriah Group",
        phone: "432-853-9783",
        location: "Midland TX",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Josh Mims",
        email: "jmims@lmbgroup.com",
        organization: "LMB Group",
        phone: "432-686-2800",
        location: "Midland TX",
        type: "Multifamily, Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Jack Oduro",
        email: "jack@moriahgroup.net",
        organization: "Moriah Group",
        phone: "512-977-8596",
        location: "Midland TX",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Corby Hodgkiss",
        email: "chodgkiss@mercer-company.com",
        organization: "Mercer Company",
        phone: "469-360-3918",
        location: "DFW",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Cody Payne",
        email: "cody.payne@colliers.com",
        organization: "Colliers",
        phone: "972-345-6500",
        location: "DFW",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Trent Agnew",
        email: "trent.agnew@jll.com",
        organization: "JLL",
        phone: "713-852-3431",
        location: "Houston",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Charlie Strauss",
        email: "charles.strauss@jll.com",
        organization: "JLL",
        phone: "713-212-6574",
        location: "Houston",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Jeff Barnes",
        email: "jeff.barnes@colliers.com",
        organization: "Colliers",
        phone: "408-218-3360",
        location: "Hollister/Gilroy/Morgan Hill",
        type: null,
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Mark Sanchez",
        email: "mark.sanchez@colliers.com",
        organization: "Colliers",
        phone: "408-313-8444",
        location: "Hollister/Gilroy/Morgan Hill",
        type: null,
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Todd Sanfilippo",
        email: "todd.sanfilippo@cbre.com",
        organization: "CBRE",
        phone: "916-847-3206",
        location: "Sacramento",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Matt Susac",
        email: "matt.susac@cbre.com",
        organization: "CBRE",
        phone: "916-342-5993",
        location: "Sacramento",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Kevin Partington",
        email: "kevin.partington@cushwake.com",
        organization: "Cushman & Wakefield",
        phone: "916-997-7728",
        location: "Sacramento",
        type: null,
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Sean Mullen",
        email: "sean.mullen@cushwake.com",
        organization: "Cushman & Wakefield",
        phone: "916-996-3945",
        location: "Sacramento",
        type: null,
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Tony Whitaker",
        email: "tony.whittaker@cbre.com",
        organization: "CBRE",
        phone: "916-425-4474",
        location: "Sacramento",
        type: null,
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Matt Cologna",
        email: "matt.cologna@cushwake.com",
        organization: "Cushman & Wakefield",
        phone: "916-837-6553",
        location: "Sacramento",
        type: null,
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Matt Post",
        email: "matt.post@cbre.com",
        organization: "CBRE",
        phone: "916-446-8756",
        location: "Sacramento",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Darren McFaddon",
        email: "dmcfadden@lee-associates.com",
        organization: "Lee & Associates",
        phone: "209-598-1180",
        location: "Stockton",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Ben Caputo",
        email: "ben.caputo@cbre.com",
        organization: "CBRE",
        phone: "408-656-0893",
        location: "San Jose",
        type: null,
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Mike Filice",
        email: "mike.filice@cbre.com",
        organization: "CBRE",
        phone: "408-568-0742",
        location: "San Jose",
        type: null,
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Mark Garner",
        email: "mark.garner@nmrk.com",
        organization: "Newmark",
        phone: "650-346-9316",
        location: "San Jose",
        type: null,
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Dave Keefe",
        email: "dave@davekeefe.com",
        organization: "Dave Keefe Real Estate Team",
        phone: "650-887-3721",
        location: "Mountain View",
        type: null,
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Thomas Loratta",
        email: "tom@tomloratta.com",
        organization: "Compass",
        phone: "808-895-5548",
        location: "Hawaii",
        type: "Residential",
        lastFollowUp: new Date("2025-03-01"),
        nextFollowUp: new Date("2025-03-01"),
        userId: null,
      },
      {
        name: "Tom Loratta (alt email)",
        email: "tomloratta@hawaii.rr.com",
        organization: "Compass",
        phone: "808-895-5548",
        location: "Hawaii",
        type: "Residential",
        lastFollowUp: new Date("2025-03-01"),
        nextFollowUp: new Date("2025-03-01"),
        userId: null,
      },
      {
        name: "Tony Villelli",
        email: "tony@villellipnw.com",
        organization: "Keller Williams",
        phone: "208-661-3044",
        location: "Spokane/CDA",
        type: null,
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Dimitre Petrov",
        email: "Dpetrov@cricommercial.com",
        organization: "CRI Commercial",
        phone: "949-996-7096",
        location: "Oakdale/Central CA",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Mark Wafer, Sr.",
        email: null,
        organization: "Newmark",
        phone: null,
        location: "Denver",
        type: null,
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Mark Wafer, Jr.",
        email: "mike.waferjr@nmrk.com",
        organization: "Newmark",
        phone: "303-260-4407",
        location: "Denver",
        type: null,
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "JJ Kramer",
        email: "jjKramer@johnlscott.com",
        organization: "John L Scott",
        phone: "Mobile: 541-840-2992; Office: 541-774-5678; Team JJ: 541-635-2992",
        location: "Oregon, Medford",
        type: "Residential",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Susan Fox",
        email: "susan@penregroup.com",
        organization: "Peninsula Real Estate Group",
        phone: "831.238.7838",  
        location: "Carmel",
        type: "Residential",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Daniel Fitch",
        email: "daniel@strockrealestate.com",
        organization: "EXP",
        phone: "831-229-2930",
        location: "Santa Cruz, Los Altos, Big Sur Area",
        type: "Multifamily/Residential",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Reuben Helick",
        email: "Reuben.Helick@cushwake.com",
        organization: "Cushman Wakefield",
        phone: "o. 831-588-9033; c. 831-647-2109",
        location: "Santa Cruz",
        type: "Commercial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Dave Anderson",
        email: "dave@andersonchristie.com",
        organization: "Anderson Christie",
        phone: "o. 831-345-1600",
        location: "Santa Cruz",
        type: "Residential",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Ron Miller",
        email: "Ron.Miller@cushwake.com",
        organization: "Cushman & Wakefield",
        phone: null,
        location: "South Bay",
        type: "Retail/Residential",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Greg Cary",
        email: "gcary@intero.com",
        organization: "Intero",
        phone: "408-464-3205",
        location: "California",
        type: "Retail/Commercial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Pete Ruiz",
        email: "peteruiz@kw.com",
        organization: "Keller Williams International / Ruiz Group",
        phone: "831-277-8712",
        location: "Northern California, Carmel, Monterey",
        type: "Residential",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "John Ream",
        email: "John.Ream@jll.com",
        organization: "JLL",
        phone: "713-826-6187",
        location: "Houston",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "John Hollenbach, Jr.",
        email: "jhollenbachjr@hcrky.com",
        organization: "Horizon Realty",
        phone: "(502) 821-4080",
        location: "Kentucky/Indiana",
        type: "Industrial/Multifamily/Office",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
      {
        name: "Michael Scarnato",
        email: "Michael.Scarnato@jll.com",
        organization: "JLL",
        phone: "214-412-0895",
        location: "Charlotte NC",
        type: "Industrial",
        lastFollowUp: new Date(),
        nextFollowUp: new Date(),
        userId: null,
      },
    ],
  });

  console.log("✅ Seeded all brokers");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });